### ISSUE TITLE
Поле минимального количества аргументов

### ISSUE THREAD

**Issue by Kuzuru** [Kuzuru/notifier-bot#10]
Нужно рассмотреть такое **узкое** (в будущем будет) место как количество передаваемых пользователем командной строке аргументов. Не все команды могут принимать `0` или `N` аргументов. Я считаю, что нам стоит ввести некое **приватное** поле `minimumArgs`, которое будет **по дефолту** всегда сверять передаваемое количество аргументов

Данное значение можно будет менять на этапе **конструктора**, то есть в `CommandInitializer(-е)`

Вероятно, в ближайшем будущем, команд будет много. Поэтому также стоит задуматься о введении некой **"таблицы"** отображений строк на экземпляры класса `ICommand`, чтобы в дальнейшем нам **не приходилось вручную** добавлять дубликат кода по типу `COMMANDS.put(...)`. Считаю, что здесь можно обойтись и простым `for` или `foreach`. Вопрос состоит в том как правильно это реализовать

Поднимаю на обсуждение

**Comment by LairTengi** [comment]
В таком случае возникают вопросы:
Что должен делать бот в том случае, если количество передаваемых команде аргументов больше или меньше, чем запланировано? И что делать с командами, которые могут принимать несколько аргументов на вход?
Наверно, наиболее простым решением в отношении первого вопроса будет выводить ошибку "Неверно введена команда", но, думаю, есть что-то более изящное

Введение таблицы отображений строк на экземпляры класса `ICommand` считаю абсолютно оправданным. Избавит нас в дальнейшем от большого количества багов.

**Comment by Kuzuru** [comment]
> В таком случае возникают вопросы: Что должен делать бот в том случае, если количество передаваемых команде аргументов больше или меньше, чем запланировано?

Устраивать техасскую резню и говорить юзеру, что:

Если меньше, то сразу выдавать "Неверно введена команда", etc.

Больше, - значит либо хорошо, либо плохо. Смотрим уже с помощью парсера
