### ISSUE TITLE
Добавление работы с ENV переменными среды

### ISSUE THREAD

**Issue by Kuzuru** [Kuzuru/notifier-bot#18]
Необходимо найти хороший пакет для работы с `.env` файлами, установить его в проект, а также протестировать его работоспособность

В `.env` мы будем хранить:

- Пароли баз данных
- Ключи
- Имена таблиц БД, хосты и другие, подлежащие скрытию данные
- Версия бота
- Имя бота, которое будет отображаться в приглашении к вводу

Вероятно, нам придется удалить информацию о версии из `Gradle` файла ( Конечно, если это вообще легально. Надо узнать об этом подробнее )

**Comment by LairTengi** [comment]
Будет сделано, капитан Сэр!!
