### ISSUE TITLE
Разработка первых тестов

### ISSUE THREAD

**Issue by Kuzuru** [Kuzuru/notifier-bot#6]
Необходимо покрыть существующий на данном этапе разработке код тестами

Предположительное покрытие на данный момент должно составлять `95%`

Необходимо **разделить** основной код от кода с тестами. Для каждой структуры необходимо выделить **свой** класс для тестирования

**Comment by Kuzuru** [comment]
Есть предложения по файловой структуре?
Возможно, существуют какие-то готовые решения?

В **ТЗ** нашего _заказчика_ указано, что мы можем использовать `JUnit`. Есть какая-то инфа по данной библиотеке?

**Comment by LairTengi** [comment]
Возьму задачу на себя. Постараюсь реализовать систему тестов с помощью JUnit
